### ISSUE TITLE
大佬，刷步失败

### ISSUE THREAD

**Issue by l666l** [TonyJiangWJ/mimotion#10]
![default](https://github.com/TonyJiangWJ/mimotion/assets/72931399/504fbcb4-26ec-4699-9dd2-cf1a3ff457a4)
![default](https://github.com/TonyJiangWJ/mimotion/assets/72931399/46b22524-54fa-4fc8-93d5-ec0472c1bfa6)

**Comment by a790186435** [comment]
token到期了，Fine-grained tokens就一年
选择token有效期，最大时长为1年。一年后需要重新续期或重建，唯一缺点

**Comment by l666l** [comment]
> token到期了，Fine-grained tokens就一年 选择token有效期，最大时长为1年。一年后需要重新续期或重建，唯一缺点

大佬，怎么操作才能恢复

**Comment by l666l** [comment]
> token到期了，Fine-grained tokens就一年 选择token有效期，最大时长为1年。一年后需要重新续期或重建，唯一缺点

但是那个github令牌今天按教程创建的选到了2025了

**Comment by a790186435** [comment]
刚才没仔细看，是接口坏了，全网使用这个接口的都刷不了步了

**Comment by a790186435** [comment]
暂时用网站吧

**Comment by l666l** [comment]
> 暂时用网站吧

还有没有自动定时刷的，大佬

**Comment by yjxzqh** [comment]
接口好像是又能用了

**Comment by l666l** [comment]
> 接口好像是又能用了

是的，又可以了，奇奇怪怪
