### ISSUE TITLE
获取apptoken失败了

### ISSUE THREAD

**Issue by leosj** [TonyJiangWJ/mimotion#11]
0125错误

**Comment by TonyJiangWJ** [comment]
看了眼接口没问题啊，你自己检查一下配置是否正确。另外我也没见你fork了仓库，无法给你排查

**Comment by leosj** [comment]
我直接本地运行代码的，发现刷不了，调试到获取apptoken那里，就是返回0125错误，接口返回的，应该是app接口有调整，你运行一下就知道了

**Comment by TonyJiangWJ** [comment]
抱歉，这个本身设计就是给github actions运行的，本地你自己研究或者搞个代理，最新执行记录并没有问题[actions run](https://github.com/TonyJiangWJ/mimotion/actions/runs/7778691077/job/21208726855)
