### ISSUE TITLE
获取accessToken失败

### ISSUE THREAD

**Issue by Mr54181452** [TonyJiangWJ/mimotion#29]
[1/1]账号：164****.com创建虚拟ip地址：223.78.28.105
已设置为随机步数范围(17822~24753) 随机值:19197
获取accessToken失败
登陆失败！

您好，在执行过程中 获取accessToken失败 ，请问一下这个是被微信拦截下来了么？

**Comment by TonyJiangWJ** [comment]
账号密码错了
