### ISSUE TITLE
步数不一致

### ISSUE THREAD

**Issue by Skykisser** [TonyJiangWJ/mimotion#40]
在设置内输入的步数是44444-45000，但是刷步直接只有36060
![Snipaste_2024-11-26_17-57-28](https://github.com/user-attachments/assets/1bf9681b-957f-473c-adc5-033d84bffbe3)
![1](https://github.com/user-attachments/assets/f144b618-9a5d-48a4-8015-4b4aeca0771c)

**Comment by TonyJiangWJ** [comment]
文档仔细看 已经写清楚了
